from flask import Flask, render_template, jsonify, request, redirect, url_for, flash, send_file
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from models import db, User, AppUsage, Boss, Equipment, DailyTask
from itsdangerous import URLSafeTimedSerializer
from functools import wraps
from datetime import datetime
import os, io, zipfile
from dotenv import load_dotenv
load_dotenv()  # read .env into os.environ

app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'default_dev_key_change_in_production')
db_url = os.environ.get('DATABASE_URL', 'sqlite:///dopamine_detox.db')
if db_url.startswith("postgres://"):
    db_url = db_url.replace("postgres://", "postgresql://", 1)
app.config['SQLALCHEMY_DATABASE_URI'] = db_url
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

login_manager = LoginManager()
login_manager.login_view = 'login'
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@app.before_request
def check_survey():
    if current_user.is_authenticated:
        if request.endpoint and request.endpoint not in ['onboarding', 'logout', 'static'] and not current_user.survey_completed:
            if not request.path.startswith('/api/'):
                return redirect(url_for('onboarding'))
from services.analytics import get_behavioral_patterns, get_daily_trends
from services.intelligence import get_intelligence_data

def require_api_token(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth_header = request.headers.get("Authorization")
        if not auth_header or not auth_header.startswith("Bearer "):
            return jsonify({"error": "Missing or invalid token"}), 401
        token = auth_header.split(" ")[1]
        serializer = URLSafeTimedSerializer(app.secret_key)
        try:
            data = serializer.loads(token, max_age=86400 * 30) # 30 days
        except Exception:
            return jsonify({"error": "Token expired or invalid"}), 401
        
        user = User.query.get(data.get("user_id"))
        if not user:
            return jsonify({"error": "User not found"}), 401
        return f(user, *args, **kwargs)
    return decorated

@app.route('/api/login', methods=['POST', 'OPTIONS'])
def api_login():
    if request.method == 'OPTIONS':
        resp = jsonify({})
        resp.headers['Access-Control-Allow-Origin'] = '*'
        resp.headers['Access-Control-Allow-Headers'] = 'Content-Type, Authorization'
        resp.headers['Access-Control-Allow-Methods'] = 'POST, OPTIONS'
        return resp

    data = request.get_json(silent=True) or {}
    username = data.get('username')
    password = data.get('password')
    user = User.query.filter_by(username=username).first()
    if user and user.check_password(password):
        serializer = URLSafeTimedSerializer(app.secret_key)
        token = serializer.dumps({"user_id": user.id})
        resp = jsonify({"access_token": token})
        resp.headers['Access-Control-Allow-Origin'] = '*'
        return resp
    resp = jsonify({"error": "Invalid credentials"})
    resp.headers['Access-Control-Allow-Origin'] = '*'
    return resp, 401

@app.after_request
def add_cors_and_ngrok_headers(response):
    """Apply CORS + ngrok bypass headers to every API response."""
    if request.path.startswith('/api/'):
        response.headers['Access-Control-Allow-Origin'] = '*'
        response.headers['Access-Control-Allow-Headers'] = 'Content-Type, Authorization'
        response.headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS'
        # Skip the ngrok browser-warning interstitial so extension fetches work
        response.headers['ngrok-skip-browser-warning'] = 'true'
    return response

@app.route('/extension-config.js')
def extension_config_js():
    """Serves a dynamically-generated config.js with the correct API base URL
    baked in from .env — used when bundling/updating the extension."""
    api_base = os.environ.get('API_BASE_URL', request.host_url.rstrip('/')).rstrip('/')
    js_content = f'''// Auto-generated by Flask — do not edit manually.
// Edit API_BASE_URL in .env and re-download the extension.
const BOOTSTRAP_ORIGIN = "{api_base}";

async function getApiBase() {{
    const {{ apiBase }} = await chrome.storage.local.get("apiBase");
    if (apiBase) return apiBase;
    try {{
        const res = await fetch(`${{BOOTSTRAP_ORIGIN}}/api/config`, {{
            cache: "no-store",
            headers: {{ "ngrok-skip-browser-warning": "true" }}
        }});
        const data = await res.json();
        const resolved = (data.api_base_url || BOOTSTRAP_ORIGIN).replace(/\/$/,"");
        await chrome.storage.local.set({{ apiBase: resolved }});
        return resolved;
    }} catch {{
        return BOOTSTRAP_ORIGIN;
    }}
}}
'''
    from flask import Response
    return Response(js_content, mimetype='application/javascript')

@app.route('/api/config')
def api_config():
    """Public endpoint — returns the server's own base URL so the extension
    can discover where to send data without any hardcoding."""
    load_dotenv(override=True)  # always re-read .env so URL changes take effect immediately
    api_base = os.environ.get('API_BASE_URL', request.host_url.rstrip('/')).rstrip('/')
    if 'ngrok' in api_base or 'vercel.app' in api_base:
        api_base = api_base.replace('http://', 'https://')
    resp = jsonify({"api_base_url": api_base})
    resp.headers['Access-Control-Allow-Origin'] = '*'
    return resp

WEBSITE_CATEGORIES = {
    # Social Media
    'facebook.com': 'Social Media', 'instagram.com': 'Social Media', 'twitter.com': 'Social Media', 
    'x.com': 'Social Media', 'linkedin.com': 'Social Media', 'tiktok.com': 'Social Media', 
    'snapchat.com': 'Social Media', 'reddit.com': 'Social Media', 'pinterest.com': 'Social Media', 
    'tumblr.com': 'Social Media', 'whatsapp.com': 'Social Media', 't.me': 'Social Media', 
    'telegram.org': 'Social Media', 'discord.com': 'Social Media', 'twitch.tv': 'Social Media',
    'quora.com': 'Social Media', 'wechat.com': 'Social Media', 'bereal.com': 'Social Media',
    
    # Entertainment (Video/Audio/Streaming/Gaming)
    'youtube.com': 'Entertainment', 'netflix.com': 'Entertainment', 'hulu.com': 'Entertainment', 
    'disneyplus.com': 'Entertainment', 'primevideo.com': 'Entertainment', 'spotify.com': 'Entertainment', 
    'applemusic.com': 'Entertainment', 'soundcloud.com': 'Entertainment', 'pandora.com': 'Entertainment',
    'hbo.com': 'Entertainment', 'max.com': 'Entertainment', 'paramountplus.com': 'Entertainment',
    'peacocktv.com': 'Entertainment', 'vimeo.com': 'Entertainment', 'dailymotion.com': 'Entertainment',
    'roblox.com': 'Entertainment', 'steampowered.com': 'Entertainment', 'epicgames.com': 'Entertainment',
    'ign.com': 'Entertainment', 'gamespot.com': 'Entertainment', 'crunchyroll.com': 'Entertainment',
    'imdb.com': 'Entertainment', 'rottentomatoes.com': 'Entertainment', '9gag.com': 'Entertainment',
    'buzzfeed.com': 'Entertainment',
    
    # Productivity / Work / Education
    'github.com': 'Productivity', 'gitlab.com': 'Productivity', 'bitbucket.org': 'Productivity',
    'stackoverflow.com': 'Productivity', 'notion.so': 'Productivity', 'slack.com': 'Productivity', 
    'trello.com': 'Productivity', 'asana.com': 'Productivity', 'jira.com': 'Productivity', 
    'atlassian.net': 'Productivity', 'figma.com': 'Productivity', 'canva.com': 'Productivity',
    'docs.google.com': 'Productivity', 'drive.google.com': 'Productivity', 'mail.google.com': 'Productivity',
    'calendar.google.com': 'Productivity', 'workspace.google.com': 'Productivity', 
    'office.com': 'Productivity', 'outlook.live.com': 'Productivity', 'microsoft365.com': 'Productivity',
    'zoom.us': 'Productivity', 'meet.google.com': 'Productivity', 'teams.microsoft.com': 'Productivity',
    'dropbox.com': 'Productivity', 'box.com': 'Productivity', 'chatgpt.com': 'Productivity',
    'openai.com': 'Productivity', 'claude.ai': 'Productivity', 'anthropic.com': 'Productivity',
    'perplexity.ai': 'Productivity', 'coursera.org': 'Productivity', 'udemy.com': 'Productivity',
    'edx.org': 'Productivity', 'khanacademy.org': 'Productivity', 'duolingo.com': 'Productivity',
    'codeacademy.com': 'Productivity', 'leetcode.com': 'Productivity', 'hackerrank.com': 'Productivity',
    'medium.com': 'Productivity', 'wikipedia.org': 'Productivity',
    
    # E-Commerce / Shopping
    'amazon.com': 'Shopping', 'ebay.com': 'Shopping', 'walmart.com': 'Shopping', 
    'target.com': 'Shopping', 'etsy.com': 'Shopping', 'aliexpress.com': 'Shopping',
    'alibaba.com': 'Shopping', 'shopify.com': 'Shopping', 'bestbuy.com': 'Shopping',
    'homedepot.com': 'Shopping', 'ikea.com': 'Shopping', 'shein.com': 'Shopping',
    'nike.com': 'Shopping', 'zara.com': 'Shopping', 'hm.com': 'Shopping',
    'flipkart.com': 'Shopping', 'myntra.com': 'Shopping',
    
    # News / Information
    'cnn.com': 'News', 'bbc.com': 'News', 'bbc.co.uk': 'News', 'nytimes.com': 'News', 
    'washingtonpost.com': 'News', 'theguardian.com': 'News', 'foxnews.com': 'News', 
    'wsj.com': 'News', 'bloomberg.com': 'News', 'reuters.com': 'News', 'forbes.com': 'News',
    'cnbc.com': 'News', 'nbcnews.com': 'News', 'npr.org': 'News', 'usatoday.com': 'News',
    'yahoo.com': 'News', 'msn.com': 'News', 'weather.com': 'News',

    # Browser / Search / Utils (defaults)
    'google.com': 'Browser', 'bing.com': 'Browser', 'duckduckgo.com': 'Browser',
    'yahoo.com': 'Browser', 'baidu.com': 'Browser', 'yandex.com': 'Browser'
}

@app.route('/api/activity', methods=['POST', 'OPTIONS'])
@require_api_token
def api_activity(user):
    # Handle CORS preflight from browser extension
    if request.method == 'OPTIONS':
        resp = jsonify({})
        resp.headers['Access-Control-Allow-Origin'] = '*'
        resp.headers['Access-Control-Allow-Headers'] = 'Content-Type, Authorization'
        resp.headers['Access-Control-Allow-Methods'] = 'POST, OPTIONS'
        return resp

    data = request.get_json(silent=True) or {}
    website_name = data.get('website_name')
    st_time = data.get('st_time')
    end_time = data.get('end_time')
    
    if not (website_name and st_time and end_time):
        return jsonify({"error": "Missing payload data"}), 400
    
    try:
        duration_mins = max(1, int((end_time - st_time) / 1000 / 60))
    except (TypeError, ValueError):
        duration_mins = 1
        
    from datetime import timedelta
    ist_now = datetime.utcnow() + timedelta(hours=5, minutes=30)
    current_hour = ist_now.hour
    interval_id = current_hour // 3
    
    # Determine the category based on the domain mapping
    category = 'Browser'  # Default fallback
    if website_name:
        domain = website_name.lower().replace('www.', '')
        category = WEBSITE_CATEGORIES.get(domain, 'Browser')
    
    usage = AppUsage(
        user_id=user.id,
        app_name=website_name,
        category=category,
        duration_minutes=duration_mins,
        interval_id=interval_id,
        timestamp=ist_now
    )
    db.session.add(usage)
    db.session.commit()
    
    resp = jsonify({"status": "success"})
    resp.headers['Access-Control-Allow-Origin'] = '*'
    return resp

@app.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))
    return render_template('home.html')

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()
        
        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for('dashboard'))
        flash('Invalid username or password')
    return render_template('login.html')

@app.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        
        if User.query.filter_by(username=username).first():
            flash('Username already exists')
            return redirect(url_for('register'))
            
        new_user = User(username=username) # hex_code generated automatically in __init__
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()
        
        login_user(new_user)
        return redirect(url_for('dashboard'))
    return render_template('register.html')

@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))

@app.route('/dashboard')
@login_required
def dashboard():
    patterns = get_behavioral_patterns(current_user.id)
    trends = get_daily_trends(current_user.id)
    return render_template('dashboard.html', patterns=patterns, trends=trends, user=current_user)

@app.route('/onboarding', methods=['GET', 'POST'])
@login_required
def onboarding():
    if current_user.survey_completed:
        return redirect(url_for('rpg_map'))
        
    if request.method == 'POST':
        # Psychological Mapping logic
        bosses_to_spawn = set()
        
        # Q1: Under stress, what is your instinct?
        q1 = request.form.get('q1')
        if q1 == 'scroll': bosses_to_spawn.add('Scroll Serpent')
        elif q1 == 'eat': bosses_to_spawn.add('Comfort Wraith')
        elif q1 == 'game': bosses_to_spawn.add('Time Thief Warlord')
        elif q1 == 'nsfw': bosses_to_spawn.add('Crimson Temptress')
        
        # Q2: When you have a massive deadline, how do you handle it?
        q2 = request.form.get('q2')
        if q2 == 'delay': bosses_to_spawn.add('Procrastination Lich')
        elif q2 == 'binge': bosses_to_spawn.add('Void Monarch')
        
        # Q3: How often do you check your phone in a social setting?
        q3 = request.form.get('q3')
        if q3 in ['often', 'always']: bosses_to_spawn.add('Validation Phantom')
        
        if not bosses_to_spawn:
            # Fallback if they answer purely positive/neutral
            bosses_to_spawn.add('Scroll Serpent')

        # Auto-infer peak time from analytics
        patterns = get_behavioral_patterns(current_user.id)
        current_user.peak_time = patterns.get('peak_window', 'Evening')
        
        for habit in bosses_to_spawn:
            # Base HP is purely narrative now, no longer tied to survey math
            new_boss = Boss(
                user_id=current_user.id,
                boss_type=habit,
                is_active=True,
                base_hp=100.0,
                current_hp=100.0,
                regen_rate=5.0,
                corruption_percent=20.0,
                last_updated_at=datetime.utcnow()
            )
            db.session.add(new_boss)
            
        current_user.survey_completed = True
        db.session.commit()
        return redirect(url_for('rpg_map'))
        
    return render_template('onboarding.html', user=current_user)

import random
def ensure_daily_tasks(user):
    today = datetime.utcnow().date()
    existing_tasks = DailyTask.query.filter_by(user_id=user.id, assigned_date=today).all()
    
    if len(existing_tasks) < 3:
        # Generate 3 new tasks
        DailyTask.query.filter_by(user_id=user.id).delete() # clear old ones
        db.session.commit()
        
        active_bosses = [b.boss_type for b in user.bosses if b.is_active]
        task_pool = [
            "Leave your phone in another room for 2 hours.",
            "Read 10 pages of a physical book.",
            "Meditate or sit in silence for 10 minutes.",
            "Complete 30 minutes of deep work with no tabs open.",
            "Do 20 pushups or equivalent physical exercise."
        ]
        
        if 'Scroll Serpent' in active_bosses: task_pool.append("Use grayscale mode on your phone for 4 hours.")
        if 'Comfort Wraith' in active_bosses: task_pool.append("Drink 2 glasses of water instead of a sugary snack.")
        if 'Procrastination Lich' in active_bosses: task_pool.append("Complete the hardest task on your to-do list BEFORE noon.")
        if 'Crimson Temptress' in active_bosses: task_pool.append("Keep bedroom door open & devices outside for 24h.")
        
        selected_tasks = random.sample(task_pool, min(3, len(task_pool)))
        for desc in selected_tasks:
            new_task = DailyTask(user_id=user.id, description=desc, assigned_date=today, coin_reward=35)
            db.session.add(new_task)
            
        db.session.commit()

import math
from datetime import timedelta

def process_regen(boss, current_time):
    if not boss.last_updated_at:
        boss.last_updated_at = current_time
        return
        
    time_elapsed = (current_time - boss.last_updated_at).total_seconds()
    regen_ticks = math.floor(time_elapsed / 120)
    
    if regen_ticks > 0:
        regen_amount = regen_ticks * (boss.base_hp * (boss.regen_rate / 100))
        boss.current_hp = min(boss.base_hp, boss.current_hp + regen_amount)
        boss.last_updated_at = boss.last_updated_at + timedelta(seconds=regen_ticks * 120)

def process_player_regen(user, current_time):
    if not user.last_health_update:
        user.last_health_update = current_time
        return
        
    time_elapsed = (current_time - user.last_health_update).total_seconds()
    regen_ticks = math.floor(time_elapsed / 120)
    
    if regen_ticks > 0 and user.current_health < user.max_health:
        regen_amount = regen_ticks * (user.max_health * (user.regen_rate / 100))
        user.current_health = min(user.max_health, user.current_health + regen_amount)
        user.last_health_update = user.last_health_update + timedelta(seconds=regen_ticks * 120)
    elif user.current_health >= user.max_health:
        user.last_health_update = current_time

BODYGUARD_STATS = {
    1: 28,   # e.g., Venom Hatchling
    2: 70,   # e.g., Shadow Viper
    3: 180,  # e.g., Scale Sentinel
    4: 300,  # e.g., Twin-Fang Hydra Spawn
    5: 530,  # e.g., Coil Reaver
    6: 1200  # The Boss itself
}

@app.route('/map')
@login_required
def rpg_map():
    now = datetime.utcnow()
    # Always ensure the user has 3 active tasks for the day
    ensure_daily_tasks(current_user)
    
    active_bosses = Boss.query.filter_by(user_id=current_user.id, is_active=True).all()
    today_tasks = DailyTask.query.filter_by(user_id=current_user.id, assigned_date=now.date()).all()
    
    process_player_regen(current_user, now)
    
    for boss in active_bosses:
        process_regen(boss, now)
        
    db.session.commit()
    
    # Check Lich conditions
    non_lich_bosses = [b for b in active_bosses if b.boss_type != 'Procrastination Lich']
    if len(non_lich_bosses) >= 1 and not current_user.lich_spawned:
        all_met = all(b.corruption_percent < 10 and b.victory_count >= 3 for b in non_lich_bosses)
        if all_met:
            lich_hp = 100 + (sum(b.corruption_percent for b in active_bosses) * 2)
            lich = Boss(
                user_id=current_user.id,
                boss_type='Procrastination Lich',
                is_active=True,
                base_hp=lich_hp,
                current_hp=lich_hp,
                regen_rate=5.0,
                corruption_percent=20.0,
                last_updated_at=now
            )
            db.session.add(lich)
            current_user.lich_spawned = True
            db.session.commit()
            active_bosses.append(lich)
            flash("The Procrastination Lich has awakened!")
            
    return render_template('map.html', user=current_user, bosses=active_bosses, tasks=today_tasks)

@app.route('/claim_task/<int:task_id>', methods=['POST'])
@login_required
def claim_task(task_id):
    task = DailyTask.query.get_or_404(task_id)
    if task.user_id == current_user.id and not task.is_completed:
        task.is_completed = True
        current_user.coins += task.coin_reward
        db.session.commit()
        flash(f"Task completed! Earned {task.coin_reward} coins.")
    return redirect(url_for('rpg_map'))

@app.route('/combat/resolve/<int:boss_id>', methods=['POST'])
@login_required
def combat_resolve(boss_id):
    boss = Boss.query.get_or_404(boss_id)
    if boss.user_id != current_user.id:
        return redirect(url_for('rpg_map'))
        
    # Phase 5: Stat-Check Logic (Shadow Fight 2 Style)
    effective_attack = current_user.attack_stat
    effective_defense = current_user.defense_stat
    
    for eq in current_user.equipment:
        if eq.effect_type == 'attack': effective_attack += eq.effect_value
        if eq.effect_type == 'defense': effective_defense += eq.effect_value
            
    player_power = effective_attack + effective_defense
    enemy_power = BODYGUARD_STATS.get(boss.current_bodyguard_index, 9999)
    
    if player_power >= enemy_power:
        # Victory against this bodyguard
        if boss.current_bodyguard_index < 6:
            boss.current_bodyguard_index += 1
            flash(f"Bodyguard Defeated! You advance deeper into the dungeon.")
        else:
            # Defeated the true boss
            boss.corruption_percent = 0
            boss.victory_count += 1
            boss.current_bodyguard_index = 1 # Reset the gauntlet
            flash(f"Massive Victory! The {boss.boss_type} has been vanquished for now.")
            
        current_user.current_streak += 1
        current_user.xp += 50
    else:
        # Defeat - Stats too low
        current_user.current_health = 0.0
        current_user.last_health_update = datetime.utcnow()
        boss.corruption_percent = min(100, boss.corruption_percent + 2)
        current_user.current_streak = 0
        boss.relapse_count += 1
        flash(f"DEFEAT! Your Power ({player_power}) was crushed by the Bodyguard ({enemy_power}). You lost all your HP and must rest to recover!")
    
    db.session.commit()
    return redirect(url_for('rpg_combat', boss_id=boss.id))

@app.route('/combat/relapse/<int:boss_id>', methods=['POST'])
@login_required
def combat_relapse(boss_id):
    boss = Boss.query.get_or_404(boss_id)
    if boss.user_id != current_user.id:
        return redirect(url_for('rpg_map'))
        
    # Explicit Surrender / Relapse
    boss.corruption_percent = min(100, boss.corruption_percent + 5)
    boss.relapse_count += 1
    current_user.current_streak = 0
    
    # Optional logic: Falling back a bodyguard level if you succumb to the habit?
    if boss.current_bodyguard_index > 1:
        boss.current_bodyguard_index -= 1
        flash("You succumbed to the urge. The corruption forces you back a dungeon level.")
    else:
        flash(f"You succumbed to the urge. Corruption increased to {boss.corruption_percent}%.")
        
    boss.last_updated_at = datetime.utcnow()
    db.session.commit()
    return redirect(url_for('rpg_combat', boss_id=boss.id))

@app.route('/combat/<int:boss_id>')
@login_required
def rpg_combat(boss_id):
    boss = Boss.query.get_or_404(boss_id)
    if boss.user_id != current_user.id:
        return redirect(url_for('rpg_map'))
    
    # Process regen visually
    now = datetime.utcnow()
    process_player_regen(current_user, now)
    process_regen(boss, now)
    db.session.commit()
    
    recovery_seconds_left = 0
    if current_user.current_health < current_user.max_health:
        import math
        regen_amount = current_user.max_health * (current_user.regen_rate / 100)
        if regen_amount > 0:
            missing_hp = current_user.max_health - current_user.current_health
            ticks_needed = math.ceil(missing_hp / regen_amount)
            total_seconds = ticks_needed * 120
            # If last_health_update is None for some reason, default to now
            last_update = current_user.last_health_update or now
            elapsed = (now - last_update).total_seconds()
            recovery_seconds_left = max(0, int(total_seconds - elapsed))
            
    return render_template('combat.html', user=current_user, boss=boss, recovery_seconds_left=recovery_seconds_left)

@app.route('/shop', methods=['GET', 'POST'])
@login_required
def shop():
    available_equipment = Equipment.query.all()
    
    if request.method == 'POST':
        equipment_id = request.form.get('equipment_id', type=int)
        if equipment_id:
            item = Equipment.query.get(equipment_id)
            if item:
                if item in current_user.equipment:
                    flash(f"You already own {item.name}.")
                elif current_user.coins >= item.cost:
                    current_user.coins -= item.cost
                    current_user.equipment.append(item)
                    db.session.commit()
                    flash(f"Successfully purchased {item.name}!")
                else:
                    flash("Not enough coins.")
        return redirect(url_for('shop'))
        
    return render_template('shop.html', user=current_user, equipment=available_equipment)

@app.route('/behavioral-intelligence')
@login_required
def behavioral_intelligence():
    intel_data = get_intelligence_data(current_user.id)
    return render_template('behavioral_intelligence.html', intel=intel_data, user=current_user)

@app.route('/analytics')
@login_required
def analytics_master():
    patterns = get_behavioral_patterns(current_user.id)
    trends = get_daily_trends(current_user.id)
    intel_data = get_intelligence_data(current_user.id)
    return render_template('analytics_master.html', patterns=patterns, trends=trends, intel=intel_data, user=current_user)

@app.route('/api/stats')
@login_required
def get_stats():
    patterns = get_behavioral_patterns(current_user.id)
    return jsonify(patterns)

from services.analytics import generate_pseudo_ai_insights

@app.route('/profile')
@login_required
def profile():
    insights = generate_pseudo_ai_insights(current_user.id)
    return render_template('profile.html', user=current_user, insights=insights)

@app.route('/friends', methods=['GET', 'POST'])
@login_required
def friends():
    if request.method == 'POST':
        hex_code = request.form.get('hex_code', '').strip().upper()
        if not hex_code:
            flash("Please enter a hex code.")
        elif hex_code == current_user.hex_code:
            flash("You cannot add yourself as a friend.")
        else:
            friend = User.query.filter_by(hex_code=hex_code).first()
            if not friend:
                flash("No user found with that hex code.")
            elif friend in current_user.friends:
                flash("You are already friends with this user.")
            else:
                current_user.friends.append(friend)
                friend.friends.append(current_user) # Mutual friendship for simplicity
                db.session.commit()
                flash(f"Successfully added {friend.username} as a friend!")
        return redirect(url_for('friends'))
    
    return render_template('friends.html', user=current_user)

from sqlalchemy import func
from models import AppUsage

@app.route('/friend/<hex_code>')
@login_required
def friend_profile(hex_code):
    # Verify the hex code belongs to a valid friend
    friend = User.query.filter_by(hex_code=hex_code).first()
    if not friend or friend not in current_user.friends:
        flash("You are not authorized to view this node's telemetry.")
        return redirect(url_for('friends'))
        
    # Calculate minimal, privacy-safe stats
    # 1. Top App
    top_app_record = db.session.query(
        AppUsage.app_name, func.sum(AppUsage.duration_minutes).label('total')
    ).filter(AppUsage.user_id == friend.id).group_by(AppUsage.app_name).order_by(db.desc('total')).first()
    
    top_app = top_app_record[0] if top_app_record else "No Data"
    
    return render_template('friend_profile.html', user=current_user, friend=friend, top_app=top_app)

import secrets
from models import Guild

@app.route('/guild', methods=['GET', 'POST'])
@login_required
def guild_dashboard():
    if request.method == 'POST':
        action = request.form.get('action')
        
        if action == 'create':
            guild_name = request.form.get('guild_name', '').strip()
            if guild_name:
                access_code = secrets.token_hex(4).upper()
                new_guild = Guild(name=guild_name, access_code=access_code, leader_id=current_user.id)
                db.session.add(new_guild)
                db.session.flush() # get ID
                current_user.guild_id = new_guild.id
                db.session.commit()
                flash(f"Guild '{guild_name}' created successfully! Access code: {access_code}")
                
        elif action == 'join':
            access_code = request.form.get('access_code', '').strip().upper()
            guild_to_join = Guild.query.filter_by(access_code=access_code).first()
            if guild_to_join:
                current_user.guild_id = guild_to_join.id
                db.session.commit()
                flash(f"Successfully joined guild '{guild_to_join.name}'!")
            else:
                flash("Invalid access code.")
                
        elif action == 'leave':
            if current_user.guild:
                if current_user.guild.leader_id == current_user.id:
                    flash("Guild leaders cannot leave their own guild yet.")
                else:
                    current_user.guild_id = None
                    db.session.commit()
                    flash("You left the guild.")
                    
        return redirect(url_for('guild_dashboard'))
        
    guild = current_user.guild
    leaderboard = []
    guild_stats = {
        "total_points": 0,
        "total_productivity_hours": 0,
        "top_distraction": "N/A"
    }
    
    if guild:
        # Sort members by points descending
        leaderboard = sorted(guild.members, key=lambda x: x.total_points, reverse=True)
        
        # Calculate Aggregated Stats
        member_ids = [m.id for m in guild.members]
        if member_ids:
            # Total Productivity Time (in hours)
            prod_mins = db.session.query(func.sum(AppUsage.duration_minutes)).filter(
                AppUsage.user_id.in_(member_ids),
                AppUsage.category == 'Productivity'
            ).scalar() or 0
            guild_stats["total_productivity_hours"] = round(prod_mins / 60, 1)
            
            # Top Distracting App (Social/Entertainment)
            top_dist_record = db.session.query(
                AppUsage.app_name, func.sum(AppUsage.duration_minutes).label('total')
            ).filter(
                AppUsage.user_id.in_(member_ids),
                AppUsage.category.in_(['Social Media', 'Entertainment'])
            ).group_by(AppUsage.app_name).order_by(db.desc('total')).first()
            
            guild_stats["top_distraction"] = top_dist_record[0] if top_dist_record else "None"
            
            guild_stats["total_points"] = sum(m.total_points for m in guild.members)
        
    return render_template('guild.html', user=current_user, guild=guild, leaderboard=leaderboard, guild_stats=guild_stats)

@app.route('/get-extension')
@login_required
def get_extension():
    return render_template('get_extension.html')

@app.route('/download-extension')
@login_required
def download_extension():
    """Zip the extension/ folder, injecting the correct API_BASE_URL into config.js."""
    ext_dir = os.path.join(app.root_path, 'extension')
    api_base = os.environ.get('API_BASE_URL', request.host_url.rstrip('/')).rstrip('/')

    # Dynamically generate config.js with the correct URL baked in
    config_js = f"""// Auto-generated config — do not edit manually.
// API_BASE_URL is read from the server's .env file at download time.
const BOOTSTRAP_ORIGIN = "{api_base}";

async function getApiBase() {{
    const {{ apiBase }} = await chrome.storage.local.get("apiBase");
    if (apiBase) return apiBase;
    try {{
        const res = await fetch(`${{BOOTSTRAP_ORIGIN}}/api/config`, {{
            cache: "no-store",
            headers: {{ "ngrok-skip-browser-warning": "true" }}
        }});
        const data = await res.json();
        const resolved = (data.api_base_url || BOOTSTRAP_ORIGIN).replace(/\\/$/, "");
        await chrome.storage.local.set({{ apiBase: resolved }});
        return resolved;
    }} catch {{
        return BOOTSTRAP_ORIGIN;
    }}
}}
"""

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        for fname in os.listdir(ext_dir):
            fpath = os.path.join(ext_dir, fname)
            if not os.path.isfile(fpath):
                continue
            if fname == 'config.js':
                # Use the dynamically generated version with the correct URL
                zf.writestr('config.js', config_js)
            else:
                zf.write(fpath, arcname=fname)
    buf.seek(0)
    return send_file(
        buf,
        mimetype='application/zip',
        as_attachment=True,
        download_name='dopamine-reset-extension.zip'
    )


if __name__ == '__main__':
    with app.app_context():
        db.create_all()
        # Create a default user if none exists
        if not User.query.first():
            default_user = User(username="default_user")
            default_user.set_password("password") # Provide a default password
            db.session.add(default_user)
            db.session.commit()
            print("Default user created.")
            
        # Seed armory if empty
        if not Equipment.query.first():
            items = [
                Equipment(name='Rusty Spoon of Discipline', type='Weapon', effect_type='attack', effect_value=5, cost=30),
                Equipment(name='Sword of Focus', type='Weapon', effect_type='attack', effect_value=15, cost=100),
                Equipment(name='Aegis of Willpower', type='Armor', effect_type='defense', effect_value=10, cost=85),
                Equipment(name='Cloak of Serenity', type='Armor', effect_type='defense', effect_value=25, cost=180),
                Equipment(name='Frozen Hourglass', type='Artifact', effect_type='regen_freeze', effect_value=1, cost=500),
                Equipment(name='Scroll of Wisdom', type='Artifact', effect_type='xp_boost', effect_value=1.5, cost=300)
            ]
            for item in items:
                db.session.add(item)
            db.session.commit()
            print("Armory has been automatically seeded.")
    
    app.run(debug=True, port=8080)
